coverage:
  status:
    project:
      default:
        threshold: 15%
    patch: off
ignore:
  - "**/*.md"
  - ".github/*"
  - "codecov.yml"
  - ".gitignore"
  - "Makefile"
  - "go.mod"
  - "go.sum"
  - "LICENSE"